modLoader="javafml" #mandatory
loaderVersion="[36.2.0,)" #mandatory
license="Mozilla Public License 2.0"
issueTrackerURL="https://github.com/bloodycooer/coo-forge/issues" #optional
[[mods]] #mandatory
modId="coo" #mandatory
version="1.16.5-1.0.0.0-beta1" #mandatory
displayName="Coo" #mandatory
updateJSONURL="https://cdn.jsdelivr.net/gh/bloodycooer/coo-forge@master/docs/versions.json" #optional
displayURL="https://www.curseforge.com/minecraft/mc-mods/coo" #optional
logoFile="coo.png" #optional
credits="Thanks for me" #optional
authors="BloodyCooer" #optional
description='''
A maverick little mod.
'''
[[dependencies.coo]] #optional
   modId="forge" #mandatory
   mandatory=true #mandatory
   versionRange="[36.2.0,)" #mandatory
   ordering="NONE"
   side="BOTH"
[[dependencies.coo]]
   modId="minecraft"
   mandatory=true
   versionRange="[1.16.5,1.17)"
   ordering="NONE"
   side="BOTH"
